# Generated by Django 5.1 on 2024-09-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('subject_code', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=100)),
                ('marks_obtained', models.IntegerField()),
                ('grade', models.CharField(max_length=2)),
                ('credits', models.FloatField()),
                ('is_revaluation', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['usn', 'semester', 'subject_code'],
                'unique_together': {('usn', 'semester', 'subject_code')},
            },
        ),
    ]
